using System.Collections.Generic;
using UnityEditor;

namespace WorldBuilder.Editor
{
    public static class WorldBuilderLocalization
    {
        public enum Language
        {
            Korean,
            English
        }

        private const string PrefKey = "WB_Language";

        private static readonly Dictionary<string, string> KoreanTable = new Dictionary<string, string>
        {
            { "tool.meshEdit", "메시 편집" },
            { "tool.prefabBrush", "프리팹 브러시" },
            { "tool.terrainPaint", "지형 페인팅" },
            { "tool.biomeSetter", "바이옴 설정" },
            { "tool.spawnEdit", "스폰 편집" },
            { "tool.export", "내보내기" },
            { "tool.voxelPaint", "복셀 페인팅" },
            { "tool.chunkGrid", "청크 그리드" },
            { "tool.heightBiome", "높이 바이옴" },
            { "tool.path", "경로" },
            { "tool.binImport", "가져오기" },
            { "tool.heatmap", "히트맵" },
            { "tool.undoHistory", "실행 취소 기록" },
            { "tool.airPocket", "에어포켓" },
            { "tool.waterCurrent", "수중 조류" },
            { "tool.bioluminescence", "생물발광" },
            { "tool.pressureZone", "수압 존" },
            { "tool.temperatureZone", "온도 존" },
            { "tool.toxicZone", "독성 존" },
            { "tool.visibilityZone", "가시거리 존" },
            { "tool.wreckage", "잔해 배치" },
            { "tool.creatureSpawn", "크리처 스폰" },
            { "tool.eventTrigger", "이벤트 트리거" },
            { "tool.depthLayer", "수심 레이어" },
            { "tool.envOverlay", "환경 오버레이" },
            { "tool.materialBatch", "머티리얼 일괄" },
            { "tool.sceneBookmark", "씬 북마크" },
            { "tool.layerBatch", "레이어 일괄 변경" },
            { "tool.sceneSearch", "씬 검색" },
            { "tool.prefabBatch", "프리팹 일괄" },
            { "tool.drawCallHeatmap", "드로우콜 히트맵" },
            { "tool.colliderVisualizer", "콜라이더 시각화" },
            { "tool.lightRange", "라이트 범위" },
            { "tool.sceneSnapshot", "씬 스냅샷" },
            { "tool.placementRule", "배치 규칙" },
            { "tool.meshOptimizer", "메시 최적화" },
            { "tool.fbxImport", "FBX 임포트" },
            { "tool.textureImport", "텍스처 임포트" },
            { "tool.shaderLiveEdit", "셰이더 라이브 편집" },
            { "tool.materialCompare", "머티리얼 비교" },
            { "tool.textureAtlas", "텍스처 아틀라스" },
            { "tool.uvVisualizer", "UV 시각화" },
            { "tool.audioVisualizer", "오디오 시각화" },
            { "tool.audioMixerPreset", "오디오 믹서 프리셋" },
            { "tool.unusedAsset", "미사용 에셋" },
            { "tool.assetReport", "에셋 리포트" },
            { "tool.sceneChange", "씬 변경사항" },
            { "tool.objectOwner", "작업자 태깅" },
            { "tool.rigidbodyBatch", "리지드바디 일괄" },
            { "tool.colliderFitter", "콜라이더 피팅" },
            { "tool.lodGenerator", "LOD 생성" },
            { "tool.lightingPreset", "라이팅 프리셋" },
            { "tool.staticFlag", "Static 플래그" },
            { "tool.objectSnap", "오브젝트 스냅" },
            { "tool.transformBatch", "Transform 일괄" },
            { "tool.terrainSculpt", "지형 조각" },
            { "header.title", "월드 빌더" },
            { "status.ready", "준비" },
            { "btn.export", "내보내기" },
            { "btn.load", "불러오기" },
            { "btn.apply", "적용" },
            { "btn.clear", "초기화" },
            { "help.title", "사용법" },
            { "help.meshEdit", "MeshFilter를 지정한 뒤 씬에서 정점을 드래그해 편집합니다. Shift+드래그로 박스 선택, 선택된 정점은 그룹으로 함께 이동합니다." },
            { "help.prefabBrush", "프리팹 목록을 채우고 씬을 클릭/드래그하면 브러시 반경 안에 프리팹을 분산 배치합니다. Erase 모드는 반경 내 프리팹 인스턴스를 삭제합니다." },
            { "help.terrainPaint", "MeshRenderer를 지정하고 씬을 칠하면 정점 컬러를 브러시로 섞습니다. 반경/강도/색을 조절하세요." },
            { "help.biomeSetter", "바이옴과 청크 크기를 정한 뒤 씬을 클릭해 청크에 바이옴을 지정합니다. Erase 모드는 지정을 해제합니다." },
            { "help.spawnEdit", "ISpawner 프리팹을 지정하고 씬을 클릭해 스포너를 배치합니다. Remove 모드는 임계 거리 내 가장 가까운 스포너를 제거합니다." },
            { "help.export", "현재 씬의 청크/스폰/복셀 데이터를 StreamingAssets/WorldBuilder/world.bin으로 내보냅니다." },
            { "help.voxelPaint", "모드(추가/감소/평활)를 고르고 씬을 칠해 복셀 밀도를 편집합니다. 결과는 복셀 스토어에 저장되어 내보내기에 반영됩니다." },
            { "help.chunkGrid", "씬 뷰 피벗 주변 반경의 청크 격자를 표시합니다. 바이옴이 지정된 청크는 초록, 나머지는 회색입니다." },
            { "help.heightBiome", "고도→바이옴 곡선을 설정하고 적용을 누르면 각 청크 높이에 따라 바이옴을 자동 할당합니다." },
            { "help.path", "컨트롤 포인트를 추가하고 씬 핸들로 드래그하면 대상 MeshFilter에 경로 메시가 생성됩니다. 너비/세그먼트를 조절하세요." },
            { "help.binImport", "world.bin을 읽어 바이옴·복셀을 복원합니다. PrefabRegistry를 지정하면 스폰 오브젝트도 함께 복원됩니다." },
            { "help.heatmap", "씬의 스포너 밀도를 색으로 표시합니다(파랑=낮음, 빨강=높음). 반경과 최대 밀도를 조절하세요." },
            { "help.undoHistory", "기록된 작업 라벨 목록입니다. 항목을 클릭하면 실행 취소하고, 초기화로 기록을 비웁니다." },
            { "help.airPocket", "크기와 라벨을 정하고 씬을 클릭해 에어포켓 볼륨을 배치합니다. 배치된 볼륨은 와이어 큐브로 표시되며 핸들로 위치를 옮길 수 있습니다." },
            { "help.waterCurrent", "강도를 정하고 씬에서 드래그하면 드래그 방향으로 조류 벡터가 설정됩니다. 화살표로 방향을 시각화합니다." },
            { "help.bioluminescence", "반경/강도/색상을 정하고 씬을 클릭해 생물발광 존을 배치합니다. 설정 색상의 와이어 디스크로 표시됩니다." },
            { "help.pressureZone", "반경/압력/데미지를 정하고 씬을 클릭해 수압 존을 배치합니다. 빨간 와이어 디스크로 표시됩니다." },
            { "help.temperatureZone", "온도와 반경을 정하고 씬을 클릭해 온도 존을 배치합니다. 양수는 주황, 0 이하는 파란 디스크로 표시됩니다." },
            { "help.toxicZone", "반경/강도/데미지를 정하고 씬을 클릭해 독성 수역을 배치합니다. 초록 와이어 디스크로 표시됩니다." },
            { "help.visibilityZone", "반경/가시거리/안개 색을 정하고 씬을 클릭해 가시거리 존을 배치합니다. 회색 반투명 디스크로 표시됩니다." },
            { "help.wreckage", "프리팹과 LOG 번호를 정하고 씬을 클릭해 잔해를 배치합니다. LOG 번호가 있으면 LOG_XXX 라벨이 표시됩니다." },
            { "help.creatureSpawn", "바이옴/프리팹 ID/밀도/반경을 정하고 씬을 클릭해 크리처 스폰 존을 배치합니다. 바이옴 색상으로 디스크가 표시됩니다." },
            { "help.eventTrigger", "이벤트 ID/반경/1회성을 정하고 씬을 클릭해 트리거 존을 배치합니다. 노란 디스크와 이벤트 ID 라벨로 표시됩니다." },
            { "help.depthLayer", "얕은물/중간/심해 깊이와 색을 정하면 씬 뷰 피벗 기준으로 수심 레이어 평면을 시각화합니다." },
            { "help.envOverlay", "오버레이 타입과 투명도를 정하면 환경 존들을 강도 기반 색상 그라디언트로 오버레이 표시합니다." },
            { "help.materialBatch", "탭으로 머티리얼 교체, 셰이더 교체, 프로퍼티 일괄 수정, 바이옴 머티리얼 프리셋을 수행합니다. 모든 작업은 실행 취소를 지원합니다." },
            { "help.sceneBookmark", "이름을 입력하고 Save를 누르면 현재 씬 카메라의 위치·회전을 북마크로 저장합니다. 목록의 항목을 클릭하면 해당 시점으로 이동하고, Delete로 삭제합니다." },
            { "help.layerBatch", "소스/타겟 레이어와 범위(씬 전체 또는 선택)를 정하고 Apply를 누르면 대상 오브젝트의 레이어를 일괄 변경합니다. 자식 포함 여부를 선택할 수 있으며 실행 취소를 지원합니다." },
            { "help.sceneSearch", "검색어와 필터 타입(이름/컴포넌트/레이어/태그)을 정하면 씬 오브젝트를 실시간 필터링합니다. 결과를 클릭하면 선택·핑되고 씬 뷰에 와이어 큐브로 강조됩니다." },
            { "help.prefabBatch", "탭에서 오버라이드 적용 또는 되돌리기를 고르고 범위(씬 전체 또는 선택)를 정한 뒤 실행하면 프리팹 인스턴스의 오버라이드를 일괄 처리합니다. 실행 취소를 지원합니다." },
            { "help.drawCallHeatmap", "Refresh로 씬의 렌더러를 수집하고 임계값을 조절하면 드로우콜 수에 따라 초록/노랑/빨강으로 오버레이 표시합니다." },
            { "help.colliderVisualizer", "Show All을 켜면 씬의 모든 콜라이더를 타입별 색상과 투명도로 와이어 표시합니다." },
            { "help.lightRange", "Show All을 켜면 씬의 모든 라이트 범위를 타입별 색상과 투명도로 표시합니다. 포인트는 디스크, 스팟은 원뿔 호로 그립니다." },
            { "help.sceneSnapshot", "이름을 입력하고 Save를 누르면 씬 오브젝트의 트랜스폼·활성 상태를 스냅샷으로 저장합니다. Restore로 복원, Delete로 삭제하며 실행 취소를 지원합니다." },
            { "help.placementRule", "규칙(소스/이웃/최소·최대 거리)을 추가하고 Validate를 누르면 규칙을 위반한 오브젝트를 찾습니다. 위반 오브젝트는 빨간 와이어 큐브로 표시됩니다." },
            { "help.meshOptimizer", "대상 MeshFilter를 지정하고 옵션을 고른 뒤 Optimize를 누르면 메시를 최적화합니다. 버텍스 수 변화를 표시하며 실행 취소를 지원합니다." },
            { "help.fbxImport", "프리셋과 대상 폴더를 정하고 Apply를 누르면 폴더 내 모든 FBX에 임포트 설정을 적용하고 다시 임포트합니다." },
            { "help.textureImport", "프리셋과 대상 폴더를 정하고 Apply를 누르면 폴더 내 모든 텍스처에 임포트 설정을 적용하고 다시 임포트합니다." },
            { "help.shaderLiveEdit", "타겟 머티리얼을 지정하면 셰이더 프로퍼티가 자동 파싱되어 타입별 필드로 표시됩니다. 값을 바꾸면 즉시 머티리얼에 반영되고 Reset으로 원본 값을 복원합니다." },
            { "help.materialCompare", "두 머티리얼을 지정하고 Compare를 누르면 프로퍼티 값을 비교합니다. 다른 값은 경고색으로 강조됩니다." },
            { "help.textureAtlas", "텍스처 목록과 아틀라스 크기·출력 경로를 정하고 Generate를 누르면 PackTextures로 아틀라스를 만들어 PNG로 저장합니다. UV 매핑 Rect가 표시됩니다." },
            { "help.uvVisualizer", "타겟 메시와 UV 채널·색상을 정하면 UV 엣지를 월드 공간에 시각화하고 시임을 강조합니다." },
            { "help.audioVisualizer", "Show All을 켜면 씬의 AudioSource를 표시합니다. 3D 소스는 min/max 거리 디스크, 2D 소스는 라벨로 표시됩니다." },
            { "help.audioMixerPreset", "프리셋을 지정하고 Save로 현재 믹서 파라미터를 저장, Apply로 프리셋 값을 믹서에 적용합니다." },
            { "help.unusedAsset", "검색 폴더를 정하고 Scan을 누르면 씬에서 참조되지 않는 미사용 에셋을 찾습니다. 각 항목은 Ping/Delete할 수 있습니다." },
            { "help.assetReport", "Scan을 누르면 씬의 텍스처·메시 사용 현황(해상도/포맷/버텍스/메모리)을 집계하고 CSV로 내보냅니다." },
            { "help.sceneChange", "Save Baseline로 현재 씬을 기준점으로 저장하고 Scan Changes로 추가/삭제/이동된 오브젝트를 비교합니다. 항목 클릭 시 선택됩니다." },
            { "help.objectOwner", "작업자 이름·색상을 정하고 Tag Selected로 선택 오브젝트에 OwnerTag를 부여합니다. 태그된 오브젝트는 작업자 색으로 표시됩니다." },
            { "help.rigidbodyBatch", "범위와 변경할 항목을 선택하고 Apply를 누르면 대상 Rigidbody에 설정을 일괄 적용합니다. 실행 취소를 지원합니다." },
            { "help.colliderFitter", "대상과 콜라이더 타입을 정하고 Fit을 누르면 메시 바운즈에 맞춰 콜라이더 크기를 자동 계산합니다. 실행 취소를 지원합니다." },
            { "help.lodGenerator", "대상 메시와 LOD 단계·비율을 정하고 Generate를 누르면 정점 클러스터링으로 감소 메시를 만들고 LODGroup을 구성합니다." },
            { "help.lightingPreset", "프리셋을 Save로 현재 RenderSettings에서 저장하고 Apply로 적용합니다. 환경광·안개 설정을 포함합니다." },
            { "help.staticFlag", "범위와 Static 플래그를 정하고 Set/Clear로 대상 오브젝트의 Static 플래그를 일괄 변경합니다. 실행 취소를 지원합니다." },
            { "help.objectSnap", "Grid 또는 Surface 모드를 켜면 선택 오브젝트를 드래그 후 그리드/표면에 스냅합니다." },
            { "help.transformBatch", "탭에서 선택 오브젝트를 정렬·분산하거나 Transform을 초기화합니다. 실행 취소를 지원합니다." },
            { "help.terrainSculpt", "모드와 브러시 반경·강도를 정하고 씬을 칠해 복셀 밀도를 조각합니다. 결과는 복셀 스토어에 저장됩니다." }
        };

        private static readonly Dictionary<string, string> EnglishTable = new Dictionary<string, string>
        {
            { "tool.meshEdit", "Mesh Edit" },
            { "tool.prefabBrush", "Prefab Brush" },
            { "tool.terrainPaint", "Terrain Painting" },
            { "tool.biomeSetter", "Biome Setter" },
            { "tool.spawnEdit", "Spawn Edit" },
            { "tool.export", "Export" },
            { "tool.voxelPaint", "Voxel Painting" },
            { "tool.chunkGrid", "Chunk Grid" },
            { "tool.heightBiome", "Height Biome" },
            { "tool.path", "Path" },
            { "tool.binImport", "Import" },
            { "tool.heatmap", "Heatmap" },
            { "tool.undoHistory", "Undo History" },
            { "tool.airPocket", "Air Pocket" },
            { "tool.waterCurrent", "Water Current" },
            { "tool.bioluminescence", "Bioluminescence" },
            { "tool.pressureZone", "Pressure Zone" },
            { "tool.temperatureZone", "Temperature Zone" },
            { "tool.toxicZone", "Toxic Zone" },
            { "tool.visibilityZone", "Visibility Zone" },
            { "tool.wreckage", "Wreckage" },
            { "tool.creatureSpawn", "Creature Spawn" },
            { "tool.eventTrigger", "Event Trigger" },
            { "tool.depthLayer", "Depth Layer" },
            { "tool.envOverlay", "Environment Overlay" },
            { "tool.materialBatch", "Material Batch" },
            { "tool.sceneBookmark", "Scene Bookmark" },
            { "tool.layerBatch", "Layer Batch" },
            { "tool.sceneSearch", "Scene Search" },
            { "tool.prefabBatch", "Prefab Batch" },
            { "tool.drawCallHeatmap", "Draw Call Heatmap" },
            { "tool.colliderVisualizer", "Collider Visualizer" },
            { "tool.lightRange", "Light Range" },
            { "tool.sceneSnapshot", "Scene Snapshot" },
            { "tool.placementRule", "Placement Rule" },
            { "tool.meshOptimizer", "Mesh Optimizer" },
            { "tool.fbxImport", "FBX Import" },
            { "tool.textureImport", "Texture Import" },
            { "tool.shaderLiveEdit", "Shader Live Edit" },
            { "tool.materialCompare", "Material Compare" },
            { "tool.textureAtlas", "Texture Atlas" },
            { "tool.uvVisualizer", "UV Visualizer" },
            { "tool.audioVisualizer", "Audio Visualizer" },
            { "tool.audioMixerPreset", "Audio Mixer Preset" },
            { "tool.unusedAsset", "Unused Asset" },
            { "tool.assetReport", "Asset Report" },
            { "tool.sceneChange", "Scene Changes" },
            { "tool.objectOwner", "Object Owner" },
            { "tool.rigidbodyBatch", "Rigidbody Batch" },
            { "tool.colliderFitter", "Collider Fitter" },
            { "tool.lodGenerator", "LOD Generator" },
            { "tool.lightingPreset", "Lighting Preset" },
            { "tool.staticFlag", "Static Flag" },
            { "tool.objectSnap", "Object Snap" },
            { "tool.transformBatch", "Transform Batch" },
            { "tool.terrainSculpt", "Terrain Sculpt" },
            { "header.title", "World Builder" },
            { "status.ready", "Ready" },
            { "btn.export", "Export" },
            { "btn.load", "Load" },
            { "btn.apply", "Apply" },
            { "btn.clear", "Clear" },
            { "help.title", "Usage" },
            { "help.meshEdit", "Assign a MeshFilter, then drag vertices in the scene to edit. Shift-drag to box-select; selected vertices move together as a group." },
            { "help.prefabBrush", "Fill the prefab list and click/drag in the scene to scatter prefabs within the brush radius. Erase mode deletes prefab instances inside the radius." },
            { "help.terrainPaint", "Assign a MeshRenderer and paint in the scene to blend vertex colors with the brush. Adjust radius, strength and color." },
            { "help.biomeSetter", "Pick a biome and chunk size, then click in the scene to assign a biome to a chunk. Erase mode removes the assignment." },
            { "help.spawnEdit", "Assign an ISpawner prefab and click in the scene to place spawners. Remove mode deletes the nearest spawner within the threshold distance." },
            { "help.export", "Exports the current scene's chunk/spawn/voxel data to StreamingAssets/WorldBuilder/world.bin." },
            { "help.voxelPaint", "Pick a mode (Add/Subtract/Smooth) and paint in the scene to edit voxel density. Results are saved to the voxel store and included in export." },
            { "help.chunkGrid", "Shows the chunk grid within a radius around the scene view pivot. Chunks with an assigned biome are green, others gray." },
            { "help.heightBiome", "Set a height-to-biome curve and press Apply to auto-assign biomes by each chunk's height." },
            { "help.path", "Add control points and drag the scene handles to generate a path mesh on the target MeshFilter. Adjust width and segments." },
            { "help.binImport", "Reads world.bin to restore biomes and voxels. Assign a PrefabRegistry to also restore spawned objects." },
            { "help.heatmap", "Visualizes spawner density by color (blue = low, red = high). Adjust radius and max density." },
            { "help.undoHistory", "A list of recorded operation labels. Click an entry to undo it; Clear empties the history." },
            { "help.airPocket", "Set size and label, then click in the scene to place an air pocket volume. Placed volumes show as wire cubes and can be moved with a handle." },
            { "help.waterCurrent", "Set strength and drag in the scene to define the current direction along the drag. The direction is visualized with an arrow." },
            { "help.bioluminescence", "Set radius, intensity and color, then click in the scene to place a bioluminescence zone, shown as a wire disc in the chosen color." },
            { "help.pressureZone", "Set radius, pressure and damage, then click in the scene to place a pressure zone, shown as a red wire disc." },
            { "help.temperatureZone", "Set temperature and radius, then click in the scene to place a temperature zone. Positive values are orange, zero or below are blue." },
            { "help.toxicZone", "Set radius, intensity and damage, then click in the scene to place a toxic zone, shown as a green wire disc." },
            { "help.visibilityZone", "Set radius, visibility and fog color, then click in the scene to place a visibility zone, shown as a translucent gray disc." },
            { "help.wreckage", "Set a prefab and LOG number, then click in the scene to place wreckage. A LOG_XXX label appears when a number is set." },
            { "help.creatureSpawn", "Set biome, prefab id, density and radius, then click in the scene to place a creature spawn zone, drawn in the biome color." },
            { "help.eventTrigger", "Set event id, radius and one-shot, then click in the scene to place a trigger zone, shown as a yellow disc with the event id label." },
            { "help.depthLayer", "Set shallow/mid/deep depths and colors to visualize depth layer planes around the scene view pivot." },
            { "help.envOverlay", "Pick an overlay type and opacity to overlay environment zones with an intensity-based color gradient." },
            { "help.materialBatch", "Use the tabs to replace materials, replace shaders, batch-edit properties, and manage biome material presets. All operations support undo." },
            { "help.sceneBookmark", "Enter a name and press Save to bookmark the current scene camera position and rotation. Click an entry to fly there; Delete removes it." },
            { "help.layerBatch", "Set source/target layers and scope (scene-wide or selection), then press Apply to batch-change object layers. Optionally include children. Supports undo." },
            { "help.sceneSearch", "Set a query and filter type (Name/Component/Layer/Tag) to filter scene objects live. Click a result to select and ping it; matches are highlighted with a wire cube." },
            { "help.prefabBatch", "Choose Apply or Revert overrides in the tabs, set the scope, and run to batch-process prefab instance overrides. Supports undo." },
            { "help.drawCallHeatmap", "Press Refresh to collect scene renderers and adjust thresholds to overlay draw-call counts in green/yellow/red." },
            { "help.colliderVisualizer", "Enable Show All to visualize every scene collider with per-type colors and opacity as wireframes." },
            { "help.lightRange", "Enable Show All to visualize every light range with per-type colors and opacity. Points draw as discs, spots as cone arcs." },
            { "help.sceneSnapshot", "Enter a name and press Save to snapshot scene object transforms and active state. Restore reapplies them, Delete removes them. Supports undo." },
            { "help.placementRule", "Add rules (source/neighbor/min-max distance) and press Validate to find rule-violating objects, highlighted with a red wire cube." },
            { "help.meshOptimizer", "Assign a target MeshFilter, choose options, and press Optimize to optimize the mesh. Shows the vertex count change and supports undo." },
            { "help.fbxImport", "Set a preset and target folder, then press Apply to apply import settings to every FBX in the folder and reimport." },
            { "help.textureImport", "Set a preset and target folder, then press Apply to apply import settings to every texture in the folder and reimport." },
            { "help.shaderLiveEdit", "Assign a target material to auto-parse shader properties into typed fields. Changes apply to the material instantly; Reset restores original values." },
            { "help.materialCompare", "Assign two materials and press Compare to diff their property values. Differing values are highlighted in a warning color." },
            { "help.textureAtlas", "Set a texture list, atlas size and output path, then press Generate to pack an atlas with PackTextures and save a PNG. UV mapping rects are shown." },
            { "help.uvVisualizer", "Set a target mesh, UV channel and color to visualize UV edges in world space and highlight seams." },
            { "help.audioVisualizer", "Enable Show All to display scene AudioSources. 3D sources show min/max distance discs; 2D sources show a label." },
            { "help.audioMixerPreset", "Assign a preset, Save to capture current mixer parameters, and Apply to write preset values back to the mixer." },
            { "help.unusedAsset", "Set a search folder and press Scan to find assets not referenced by the scene. Each entry can be pinged or deleted." },
            { "help.assetReport", "Press Scan to aggregate scene texture/mesh usage (resolution/format/vertices/memory) and export it as CSV." },
            { "help.sceneChange", "Save Baseline to capture the current scene, then Scan Changes to diff added/removed/moved objects. Click an entry to select it." },
            { "help.objectOwner", "Set an owner name and color, then Tag Selected to assign an OwnerTag to the selection. Tagged objects are drawn in the owner color." },
            { "help.rigidbodyBatch", "Choose scope and which fields to change, then press Apply to batch-apply settings to target Rigidbodies. Supports undo." },
            { "help.colliderFitter", "Choose a target and collider type, then press Fit to size the collider to the mesh bounds. Supports undo." },
            { "help.lodGenerator", "Set a target mesh and LOD levels/ratios, then press Generate to build reduced meshes via vertex clustering and set up a LODGroup." },
            { "help.lightingPreset", "Save captures current RenderSettings into a preset; Apply writes it back. Includes ambient and fog settings." },
            { "help.staticFlag", "Choose scope and static flags, then Set/Clear to batch-change object static flags. Supports undo." },
            { "help.objectSnap", "Enable Grid or Surface mode to snap the dragged selection to the grid or a surface." },
            { "help.transformBatch", "Use the tabs to align/distribute the selection or reset its transform. Supports undo." },
            { "help.terrainSculpt", "Set a mode and brush radius/strength, then paint in the scene to sculpt voxel density. Results are saved to the voxel store." }
        };

        private static Language current = (Language)EditorPrefs.GetInt(PrefKey, (int)Language.Korean);

        public static Language Current
        {
            get => current;
            set
            {
                current = value;
                EditorPrefs.SetInt(PrefKey, (int)value);
            }
        }

        public static string Get(string key)
        {
            Dictionary<string, string> table = current == Language.Korean ? KoreanTable : EnglishTable;
            return table.TryGetValue(key, out string value) ? value : key;
        }
    }
}
